<?php echo $this->doctype() ?>
<html>
<head>
    <?php $fc = Zend_Controller_Front::getInstance(); ?>
    <?php $this->user = Zend_Auth::getInstance()->getIdentity(); ?>
    <?php echo $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8')?>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink()->appendStylesheet($fc->getBaseUrl().'/css/normalize.css')
                                ->appendStylesheet($fc->getBaseUrl().'/css/main.css')
                                ->appendStylesheet($fc->getBaseUrl().'/css/jquery-ui.css')
                                ->appendStylesheet($fc->getBaseUrl().'/css/jquery-ui.theme.css')
                                ->appendStylesheet($fc->getBaseUrl().'/css/bootstrap.css')
                                ->appendStylesheet($fc->getBaseUrl().'/css/bootstrap-theme.css') ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript()->appendFile($fc->getBaseUrl().'/js/jquery-1.11.1.js')
                                  ->appendFile($fc->getBaseUrl().'/js/jquery-ui.js')
                                  ->appendFile($fc->getBaseUrl().'/js/latinise.js')
                                  ->appendFile($fc->getBaseUrl().'/js/application.js')
                                  ->appendFile($fc->getBaseUrl().'/js/bootstrap.js')
                                  ->appendFile($fc->getBaseUrl().'/js/maskedInput.js')
                                  ->appendScript('application.topMenuRegister();', 'text/javascript')
                                  ->appendScript('application.registerFormSubmit();', 'text/javascript')
//                                  ->appendScript('application.loading();', 'text/javascript')
//                                  ->appendScript('application.setActiveMenu();', 'text/javascript')
//                                  ->prependScript('activePath = "'.$this->activeMenu.'"')
//                                  ->appendScript('application.leftMenu();', 'text/javascript');
            ?>
</head>
    <body>
        <div id="loginArea" style="width: 60%; float: right;">
            <?php
            if(isset($this->userData)){
                
            ?>
            <p class="navbar-text navbar-right">
                <a class="btn btn-danger pull-right" style="margin-right: 50px" href="/index/logout" role="button">
                    Logout
                </a>
            </p>
            <p class="navbar-text navbar-right" style="margin-right: 50px; padding: 7px">
                Signed in as 
                <!--<a href="user/details" class="navbar-link">-->
                <a href="#" class="navbar-link">
                    <?php 
                        echo $this->userData->first_name.' '.$this->userData->last_name
                    ?>
                </a>
            </p>
            
            <?php 
            } else {
                echo $this->formLogin;
            } ?>
        </div>
        <ul class="nav nav-tabs">
            <li role="presentation" class="active"><a href="/main/home">Home</a></li>
            <li role="presentation" ><a href="/main/active">Active Routes</a></li>
            <li role="presentation" ><a href="#">Hom3</a></li>
            <li role="presentation" class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-expanded="false">
                Dropdown <span class="caret"></span>
              </a>
              <ul class="dropdown-menu" role="menu">

              </ul>
            </li>
        </ul>
        
        
        <div id="mainContent" style="width: 100%; height: 500px;">
            <?php echo $this->layout()->content ?> 
        </div>
        
    </body>
</html>


<div id="dialogRegister" title="Register" style="margin:0px; padding:0px; overflow:hidden">
    <?php 
        echo $this->formRegister;
    ?>
</div>

<div id="successInfo" title="Success!" style="margin:0px; padding:0px; overflow:hidden">
    <p>You have successfully registered!</p>
</div>