<?php echo $this->doctype() ?>
<html style="overflow-y:scroll;">
<head>
    <?php $fc = Zend_Controller_Front::getInstance(); ?>
    <?php $this->user = Zend_Auth::getInstance()->getIdentity(); ?>
    <?php echo $this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8')?>
    <?php echo $this->headTitle() ?>
    <?php echo $this->headLink()->appendStylesheet($fc->getBaseUrl().'/css/normalize.css')
                                ->appendStylesheet($fc->getBaseUrl().'/css/main.css')
                                ->appendStylesheet($fc->getBaseUrl().'/css/jquery-ui.css')
                                ->appendStylesheet($fc->getBaseUrl().'/css/jquery-ui.theme.css')
                                ->appendStylesheet($fc->getBaseUrl().'/css/bootstrap.css')
                                ->appendStylesheet($fc->getBaseUrl().'/css/bootstrap-theme.css') ?>
    <?php echo $this->headStyle() ?>
    <?php echo $this->headScript()->appendFile($fc->getBaseUrl().'/js/jquery-1.11.1.js')
                                  ->appendFile($fc->getBaseUrl().'/js/jquery-ui.js')
                                  ->appendFile($fc->getBaseUrl().'/js/latinise.js')
                                  ->appendFile($fc->getBaseUrl().'/js/application.js')
                                  ->appendFile($fc->getBaseUrl().'/js/bootstrap.js')
                                  ->appendFile($fc->getBaseUrl().'/js/maskedInput.js')
                                  ->appendScript('application.topMenuRegister();', 'text/javascript')
                                  ->appendScript('application.registerFormSubmit();', 'text/javascript')
                                  ->appendScript('application.loginFormSubmit();', 'text/javascript')
                                  ->appendScript('application.setActiveMenu();', 'text/javascript')
                                  ->prependScript('activeMenu = "'.$this->activeMenu.'"'); ?>

                                    <script src="https://maps.googleapis.com/maps/api/js?v=3.exp"></script>
</head>
    <body>
        <div id="loginArea" style="width: 60%; float: right;">
            <?php
            if(isset($this->userData)){
                
            ?>
            <p class="navbar-text navbar-right">
                <a class="btn btn-danger pull-right" style="margin-right: 50px" href="/index/logout" role="button">
                    Logout
                </a>
            </p>
            <p class="navbar-text navbar-right" style="margin-right: 50px; padding: 7px">
                Signed in as 
                <!--<a href="user/details" class="navbar-link">-->
                <a href="#" class="navbar-link">
                    <?php 
                        echo $this->userData->first_name.' '.$this->userData->last_name
                    ?>
                </a>
            </p>
            
            <?php 
            } else {
                echo $this->formLogin;
            } ?>
        </div>
        <ul class="nav nav-tabs">
            <li role="presentation" class="active" ><a href="/main/home" style="font-size: 25px !important; background-color: transparent;  border: none;">MyWay</a></li>
            <li role="presentation" ><a href="/main/active" style="margin-top: 15px;">Active Routes</a></li>

            <?php 
            if(isset($this->user) && $this->user->driver_flag === "1"){
            ?>
                <li role="presentation"><a href="/main/new" style="margin-top: 15px;">New Route</a></li>
            <?php } else { ?>
                <li role="presentation" class="disabled"><a href="#" style="margin-top: 15px;">New Route</a></li>
            <?php } ?>
                
            <?php 
            if(isset($this->user)){
            ?>
                <li role="presentation" ><a href="/main/myroutes" style="margin-top: 15px;">My Routes</a></li>
            <?php } else { ?>
                <li role="presentation" class="disabled"><a href="#" style="margin-top: 15px;">My Routes</a></li>
            <?php } ?>
            
           
        </ul>
        
        
        <div id="mainContent" style="width: 100%; height: 500px;">
            <?php echo $this->layout()->content ?> 
        </div>
        
    </body>
</html>


<div id="dialogRegister" title="Register" style="margin:0px; padding:0px; overflow:hidden">
    <?php 
        echo $this->formRegister;
    ?>
</div>

<div id="successInfo" title="Success!" style="margin:0px; padding:0px; overflow:hidden">
    <p>You have successfully registered!</p>
</div>

<style>
.ui-dialog .ui-dialog-titlebar-close{
background-image: url('../images/app/check_off.png') !important;
background-position-x: -2px !important;
background-position-y: -2px !important;
border-radius: 9px;
}

input:hover{
border-color: #b94a48 !important;
box-shadow: none !important;
}
input:focus{
border-color: #b94a48 !important;
box-shadow: none !important;
}
select:focus{
border-color: #b94a48 !important;
box-shadow: none !important;
}
select:hover{
border-color: #b94a48 !important;
box-shadow: none !important;
}
#password{
    border-radius : 5px !important;
    box-shadow: none !important;
    outline: none;
}
#email{
    border-radius : 5px !important;
    box-shadow: none !important;
    outline: none;
}
#submitUser{
    background-color: #d9534f ! important;
    background-image: none !important;
    border: 0px;
}

.btn{

background-color: #d9534f  !important;
background-image: none !important;
border-color: none !important;
box-shadow: none !important;
border: 0px;

}
body{
background: linear-gradient(to right, #dadada 0%,#ffffff 20%,#ffffff 80%,#dadada 100%);
}

.jumbotron{
    background-color: white !important;
    box-shadow: 10px 10px 65px black;
}

#loginArea{
    margin-top: 10px  !important;
}
img{
    border-radius: 20px;
}

</style>
