<div class="container" style="margin-top: 10px;">
   
   <div class="input-group" style="margin-bottom:10px">
  <span class="input-group-addon">From</span><input type="text" class="form-control"/>
  <span class="input-group-addon">To</span> <input type="text" class="form-control"/>
  <span class="input-group-addon">Date</span>  <input type="text" class="form-control" id="jqDpiker"/>
 
</div>
  <script>
 $(function() {

     $("#jqDpiker").datepicker({ dateFormat: 'dd.mm.yy', minDate: 'dateToday'});
                
  });
</script>

  <?php 

 

  foreach($this->results as $results){
     echo " <div class='jumbotron'>";
     $fname;
     $lanme;
     $id;
     $role_id;
        foreach($results as $key => $result){
            if ($key=="start"){
            echo '<p>From:  '.$result.'</p>';
              }
               if ( $key=="finish" ){
            echo '<p>To: '.$result.'</p>';
              }
               if ( $key=="first_name" || $key=="last_name"){
           $fname=$result;
              }
              if (  $key=="last_name"){
             $lname=$result;
              }
              if (  $key=="id"){
             $role_id=$result;
              }
              if (  $key=="id"){
             $id=$result;
              }
              if (  $key=="telephone"){
          echo '<p> Telephone: '.$result.'</p>';
              }
               if (  $key=="date"){
        echo '<p> Date: '.$result.'</p>';
              }
         
        }
         echo '<p> Name : '.$fname." ".$lname.'</p>';
        echo "<p><a class='btn btn-primary btn-lg' href='/go/".$id."/".$role_id."' role='button'>Learn more</a></p>";
         echo ' </div >';
    }
  ?>
     
</div>
<div>
