

<div class="container" style="margin-top: 10px;">
   
   <div class="input-group" style="margin-bottom:10px">
  <span class="input-group-addon">From</span><input type="text" id="fromFilter" class="form-control"/>
  <span class="input-group-addon">To</span> <input type="text" id="toFilter" class="form-control"/>
  <span class="input-group-addon">Date</span>  <input type="text" id="dateFilter" class="form-control"/>
 
</div>
<script type="text/javascript">

    $(function() {
        $("#dateFilter").datepicker({ dateFormat: 'dd.mm.yy', minDate: 'dateToday'}); 
        ajaxRequest();
        
        $('#successInfo, #failInfo, #yoursInfo').dialog({
            autoOpen: false,
            closeOnEscape: true,
            beforeclose: function (event, ui) { return false; },
            buttons: [
            {
               text: "OK",
               "class": "btn btn-danger",
               click: function() { 
                  $(this).dialog("close"); 
               }
            }
            ],
            width: 350,
            height: 200,
            close: function (event, ui){
                event.stopPropagation();
            },
            resizable: false,
            draggable: false,
            modal: true 
        }); 
        
        $('#fromFilter, #toFilter').keyup(function(){
           delay(function(){
               ajaxRequest();
           }, 400); 
        });
        
        $('.asignPass').click(function(){
            $.ajax({
                type: 'POST',
                url: '/main/addpass',
                data: { route: $(this).attr('data-id'), pass: $(this).attr('data-pass')},
                dataType: 'json',
                async: false, 
                cache: false,
                success: function(data){
                    if(data !== 404 && data !== 'exista' && data !== 'yours'){
                        $('#successInfo').dialog('open');
                        ajaxRequest();
                    } else if(data == 'exista'){
                        $('#failInfo').dialog('open');
                    } else if(data == 'yours'){
                        $('#yoursInfo').dialog('open');
                    } 
                }
            });
            
        });
        
        $('#dateFilter').change(function(){
           delay(function(){
               ajaxRequest();
           }, 400); 
        });
        
     });
     
var delay = (function(){
  var timer = 0;
  return function(callback, ms){
    clearTimeout (timer);
    timer = setTimeout(callback, ms);
  };
})();

function ajaxRequest(){
    $.ajax({
        type: 'POST',
        url: '/main/filter',
        data: { from: $('#fromFilter').val(), to: $('#toFilter').val(), date: $('#dateFilter').val() },
        dataType: 'json',
        async: false, 
        cache: false,
        success: function(data){

        $("#mustdelete").empty();
            jQuery.each( data, function( i, val ) {
//                console.log(val);
                var myVar = "";
                if(val.passenger==0) { myVar="disabled"; }
                <?php 
                    if(!$this->userId){ ?> myVar="disabled"; <?php }
                ?>
    var out =  "<div class='jumbotron'><p>From:  "+val.start+"<div class='pull-right'>Passengers remaining: "+val.passenger+"</div>"+"</p><p>To: "+val.finish+"</p><p> Date: "+val.date+"</p><p> Telephone: "+val.telephone+"</p><p> Name : "+val.first_name+" " +val.last_name+"</p><p>\n\
<button class='btn btn-primary btn-lg asignPass' data-id='"+val.route_id+"' data-pass='"+val.passenger+"' role='button'"+ myVar +">Let\'s Carpool!</button>\n\
</p> <img src='../images/app/car.jpg' alt='first' style='max-width: 150px; max-height: 150px;margin-top: -165px;' class='pull-right'></div>";
    $("#mustdelete").append(out);
            });
        }          
    }); 
}


</script>
<div id="mustdelete">
</div>
 

  
 </div>    
</div>
<div>
    
    
<div id="successInfo" title="Success!" style="margin:0px; padding:0px; overflow:hidden">
    <br>
    <p style="text-align: center">You have successfully been added to this route!</p>
</div>
    
<div id="failInfo" title="Warning!" style="margin:0px; padding:0px; overflow:hidden">
    <br>
    <p style="text-align: center">You are already expected to take part!</p>
</div>
    
<div id="yoursInfo" title="Warning!" style="margin:0px; padding:0px; overflow:hidden">
    <br>
    <p style="text-align: center">You cannot carpool in your own route!</p>
</div>



   

  