<div class="container" style="margin-top: 10px;">
   
   <div class="input-group" style="margin-bottom:10px">
  <span class="input-group-addon">From</span><input type="text" id="fromFilter" class="form-control"/>
  <span class="input-group-addon">To</span> <input type="text" id="toFilter" class="form-control"/>
  <span class="input-group-addon">Date</span>  <input type="text" id="dateFilter" class="form-control"/>
 
</div>
<script type="text/javascript">

    $(function() {
        $("#dateFilter").datepicker({ dateFormat: 'dd.mm.yy', minDate: 'dateToday'}); 
        ajaxRequest();
        $('#fromFilter, #toFilter').keyup(function(){
           delay(function(){
               ajaxRequest();
           }, 400); 
        });
        
        $('#dateFilter').change(function(){
           delay(function(){
               ajaxRequest();
           }, 400); 
        });
        
     });
     
var delay = (function(){
  var timer = 0;
  return function(callback, ms){
    clearTimeout (timer);
    timer = setTimeout(callback, ms);
  };
})();

function ajaxRequest(){
    $.ajax({
        type: 'POST',
        url: '/main/filter',
        data: { from: $('#fromFilter').val(), to: $('#toFilter').val(), date: $('#dateFilter').val() },
        dataType: 'json',
        async: false, 
        cache: false,
        success: function(data){

            $("#mustdelete").empty();
            jQuery.each( data, function( i, val ) {
                console.log(val);
                var myVar = "";
                if(val.passenger==0) { myVar="disabled"; }
    var out =  "<div class='jumbotron'><p>From:  "+val.start+"<div class='pull-right'>Passengers remaining: "+val.passenger+"</div>"+"</p><p>To: "+val.finish+"</p><p> Date: "+val.date+"</p><p> Telephone: "+val.telephone+"</p><p> Name : "+val.first_name+" " +val.last_name+"</p><p><a class='btn btn-primary btn-lg' href='/go/"+val.user_id+"/"+val.id+"' role='button'"+ myVar +">Learn more</a></p> </div>";
    $("#mustdelete").append(out);
            });
        }          
    }); 
}


</script>
<div id="mustdelete">
</div>
 

  
 </div>    
</div>
<div>
