<table class="table table-condensed">
    <thead>
        <tr>
            <th>Trip No.</th>
            <th>Departure</th>
            <th>Arrival</th>
            <th>Date</th>
            <th>Completed</th>
        </tr>
    </thead>
    <tbody>
        
    </tbody>
</table>


<?php   

foreach($this->results as $results){
    foreach($results as $key => $result){
        echo $key.': '.$result.'<br>';
    }
}