<script>
    $(document).ready(function(){
       $('.btn-update-route').click(function(){
          ajaxRequest($(this).attr('data'));
       }); 
    });

function ajaxRequest(data){
    $.ajax({
        type: 'POST',
        url: '/main/updateroute',
        data: { data : data },
        dataType: 'json',
        async: false, 
        cache: false,
        success: function(data){
            location.reload();
        }          
    }); 
}
</script>

<div class="container" style="margin-top: 30px;">
<?php if($this->driver){ ?>
<h4 style="color: #d9534f;">Routes as Driver: </h4>
<table class="table table-condensed">
    <thead>
        <tr>
            <th>Trip No.</th>
            <th>Departure</th>
            <th>Arrival</th>
            <th>Date</th>
            <th>Status</th>
            <th>Control Area</th>
        </tr>
    </thead>
    <tbody>
        <?php   
        $i = 0;
        if($this->results){
            foreach($this->results as $results){
                $i++;
                if($results['status'] == 'Complete'){
                    echo '<tr class="success">';
                } else {
                    echo '<tr>';
                }

                    echo '<td>'.$i.'</td>';
                    echo '<td>'.$results['start'].'</td>';
                    echo '<td>'.$results['finish'].'</td>';
                    echo '<td>'.$results['date'].'</td>';
                    echo '<td>'.$results['status'].'</td>';

                    if($results['status'] == 'In Progress'){
                        echo '<td><button type="button" class="btn btn-success btn-sm btn-update-route" '
                        . 'data="'.$results['route_id'].'">Complete</button></td>';
                    } else {
                        echo '<td></td>';
                    }
                echo '</tr>';
            }
        }
        
        ?>
    </tbody>
</table>
<?php } ?>

<h4 style="color: #d9534f;">Routes as Passsanger: </h4>
<table class="table table-condensed">
    <thead>
        <tr>
            <th>Trip No.</th>
            <th>Departure</th>
            <th>Arrival</th>
            <th>Date</th>
        </tr>
    </thead>
    <tbody>
        <?php   
        $i = 0;
        if($this->passangerResults){
            foreach($this->passangerResults as $results){
                $i++;
                if($results['status'] == 'Complete'){
                    echo '<tr class="success">';
                } else {
                    echo '<tr>';
                }

                    echo '<td>'.$i.'</td>';
                    echo '<td>'.$results['start'].'</td>';
                    echo '<td>'.$results['finish'].'</td>';
                    echo '<td>'.$results['date'].'</td>';
                echo '</tr>';
            }
        }
        
        ?>
    </tbody>
</table>
<div>

